coverage:
  ignore:
    - docs/*
    - packages/ability-attributes/src/*
    - packages/accessibility/src/behaviors/*
    - packages/react/src/themes/*
    - packages/react/src/styles/*
    - packages/react/test/*
