const debugData = {
  variables: [
    {
      input: {
        padding: '0 1.4286rem',
        height: '2.2857rem',
        minWidth: '6.8571rem',
        loadingMinWidth: '8.4286rem',
        maxWidth: '20rem',
        borderRadius: 'siteVariables[borderRadius]',
        contentFontSize: 'siteVariables[fontSizes.medium]',
        contentFontWeight: 'siteVariables[fontWeightSemibold]',
        contentLineHeight: 'siteVariables[lineHeightMedium]',
        color: 'siteVariables[colors.grey.750]',
        colorHover: 'siteVariables[colors.grey.750]',
        colorFocus: 'siteVariables[colors.grey.750]',
        colorDisabled: 'siteVariables[colorScheme.brand.foregroundDisabled]',
        backgroundColor: 'siteVariables[colors.white]',
        backgroundColorActive: 'siteVariables[colors.grey.200]',
        backgroundColorHover: 'siteVariables[colors.grey.50]',
        backgroundColorFocus: 'siteVariables[colors.grey.200]',
        backgroundColorDisabled: 'siteVariables[colors.grey.150]',
        borderColor: 'siteVariables[colors.grey.200]',
        borderColorHover: 'siteVariables[colors.grey.250]',
        borderColorDisabled: 'transparent',
        primaryColor: 'siteVariables[colors.white]',
        primaryColorHover: 'siteVariables[colors.white]',
        primaryColorFocus: 'siteVariables[colors.white]',
        primaryBackgroundColor: 'siteVariables[colors.brand.600]',
        primaryBackgroundColorActive: 'siteVariables[colors.brand.900]',
        primaryBackgroundColorHover: 'siteVariables[colors.brand.800]',
        primaryBackgroundColorFocus: 'siteVariables[colors.brand.800]',
        primaryBorderColor: 'transparent',
        circularBorderRadius: '71.3571rem',
        circularColor: 'siteVariables[colors.grey.500]',
        circularColorActive: 'siteVariables[colors.white]',
        circularBackgroundColor: 'transparent',
        circularBackgroundColorActive: 'siteVariables[colors.grey.500]',
        circularBackgroundColorHover: 'siteVariables[colors.grey.450]',
        circularBackgroundColorFocus: 'siteVariables[colors.grey.450]',
        circularBorderColor: 'siteVariables[colors.grey.500]',
        circularBorderColorHover: 'transparent',
        circularBorderColorFocus: 'transparent',
        textColor: 'siteVariables[colorScheme.default.foreground1]',
        textColorHover: 'siteVariables[colorScheme.brand.foreground1]',
        textPrimaryColor: 'siteVariables[colorScheme.brand.foreground]',
        textPrimaryColorHover: 'siteVariables[colorScheme.brand.foreground1]',
        textColorDisabled: 'siteVariables[colorScheme.brand.foregroundDisabled1]',
        boxShadow: 'siteVariables[shadowLevel1]',
        loaderBorderSize: '0.1429rem',
        loaderSize: '1.4286rem',
        loaderSvgHeight: '87.1429rem',
        loaderSvgAnimationHeight: '-85.7143rem',
        sizeSmallContentFontSize: 'siteVariables[fontSizes.small]',
        sizeSmallContentLineHeight: 'siteVariables[lineHeightSmall]',
        sizeSmallHeight: '1.7143rem',
        sizeSmallMinWidth: '5.1429rem',
        sizeSmallPadding: '0 0.5714rem',
        sizeSmallLoaderBorderSize: '0.1429rem',
        sizeSmallLoaderSize: '1.0714rem',
        sizeSmallLoaderSvgHeight: '63.9286rem',
        sizeSmallLoaderSvgAnimationHeight: '-62.8571rem',
      },
      resolved: {
        padding: '0 1.4286rem',
        height: '2.2857rem',
        minWidth: '6.8571rem',
        loadingMinWidth: '8.4286rem',
        maxWidth: '20rem',
        borderRadius: '2px',
        contentFontSize: '1rem',
        contentFontWeight: 600,
        contentLineHeight: 1.4286,
        color: '#252423',
        colorHover: '#252423',
        colorFocus: '#252423',
        colorDisabled: '#C8C6C4',
        backgroundColor: '#fff',
        backgroundColorActive: '#E1DFDD',
        backgroundColorHover: '#FAF9F8',
        backgroundColorFocus: '#E1DFDD',
        backgroundColorDisabled: '#EDEBE9',
        borderColor: '#E1DFDD',
        borderColorHover: '#C8C6C4',
        borderColorDisabled: 'transparent',
        primaryColor: '#fff',
        primaryColorHover: '#fff',
        primaryColorFocus: '#fff',
        primaryBackgroundColor: '#6264A7',
        primaryBackgroundColorActive: '#33344A',
        primaryBackgroundColorHover: '#464775',
        primaryBackgroundColorFocus: '#464775',
        primaryBorderColor: 'transparent',
        circularBorderRadius: '71.3571rem',
        circularColor: '#484644',
        circularColorActive: '#fff',
        circularBackgroundColor: 'transparent',
        circularBackgroundColorActive: '#484644',
        circularBackgroundColorHover: '#605E5C',
        circularBackgroundColorFocus: '#605E5C',
        circularBorderColor: '#484644',
        circularBorderColorHover: 'transparent',
        circularBorderColorFocus: 'transparent',
        textColor: '#484644',
        textColorHover: '#6264A7',
        textPrimaryColor: '#6264A7',
        textPrimaryColorHover: '#6264A7',
        textColorDisabled: '#C8C6C4',
        boxShadow: '0 .2rem .4rem -.075rem rgba(0, 0, 0, .1)',
        loaderBorderSize: '0.1429rem',
        loaderSize: '1.4286rem',
        loaderSvgHeight: '87.1429rem',
        loaderSvgAnimationHeight: '-85.7143rem',
        sizeSmallContentFontSize: '0.8571rem',
        sizeSmallContentLineHeight: 1.3333,
        sizeSmallHeight: '1.7143rem',
        sizeSmallMinWidth: '5.1429rem',
        sizeSmallPadding: '0 0.5714rem',
        sizeSmallLoaderBorderSize: '0.1429rem',
        sizeSmallLoaderSize: '1.0714rem',
        sizeSmallLoaderSvgHeight: '63.9286rem',
        sizeSmallLoaderSvgAnimationHeight: '-62.8571rem',
      },
    },
    {
      input: { color: 'siteVariables[colors.red.500]' },
      resolved: { color: '#A72037' },
    },
  ],
}

export default debugData
