const debugData = {
  componentName: 'Button',
  componentVariables: [
    {
      padding: '0 1.4286rem',
      height: '2.2857rem',
      minWidth: '6.8571rem',
      loadingMinWidth: '8.4286rem',
      maxWidth: '20rem',
      borderRadius: '2px',
      contentFontSize: '1rem',
      contentFontWeight: 600,
      contentLineHeight: 1.4286,
      color: '#252423',
      colorHover: '#252423',
      colorFocus: '#252423',
      colorDisabled: '#605E5C',
      backgroundColor: '#fff',
      backgroundColorActive: '#E1DFDD',
      backgroundColorHover: '#FAF9F8',
      backgroundColorFocus: '#E1DFDD',
      backgroundColorDisabled: '#EDEBE9',
      borderColor: '#E1DFDD',
      borderColorHover: '#C8C6C4',
      borderColorDisabled: 'transparent',
      primaryColor: '#fff',
      primaryColorHover: '#fff',
      primaryColorFocus: '#fff',
      primaryBackgroundColor: '#6264A7',
      primaryBackgroundColorActive: '#33344A',
      primaryBackgroundColorHover: '#464775',
      primaryBackgroundColorFocus: '#464775',
      primaryBorderColor: 'transparent',
      circularBorderRadius: '71.3571rem',
      circularColor: '#484644',
      circularColorActive: '#fff',
      circularBackgroundColor: 'transparent',
      circularBackgroundColorActive: '#484644',
      circularBackgroundColorHover: '#605E5C',
      circularBackgroundColorFocus: '#605E5C',
      circularBorderColor: '#484644',
      circularBorderColorHover: 'transparent',
      circularBorderColorFocus: 'transparent',
      textColor: '#C8C6C4',
      textColorHover: '#A6A7DC',
      textPrimaryColor: '#A6A7DC',
      textPrimaryColorHover: '#A6A7DC',
      textColorDisabled: '#605E5C',
      boxShadow: '0 .2rem .4rem -.075rem rgba(0, 0, 0, .25)',
      loaderBorderSize: '0.1429rem',
      loaderSize: '1.4286rem',
      loaderSvgHeight: '87.1429rem',
      loaderSvgAnimationHeight: '-85.7143rem',
      sizeSmallContentFontSize: '0.8571rem',
      sizeSmallContentLineHeight: 1.3333,
      sizeSmallHeight: '1.7143rem',
      sizeSmallMinWidth: '5.1429rem',
      sizeSmallPadding: '0 0.5714rem',
      sizeSmallLoaderBorderSize: '0.1429rem',
      sizeSmallLoaderSize: '1.0714rem',
      sizeSmallLoaderSvgHeight: '63.9286rem',
      sizeSmallLoaderSvgAnimationHeight: '-62.8571rem',
    },
    {
      backgroundColor: 'green',
    },
    {
      padding: '0 1.4286rem',
      height: '2.2857rem',
      minWidth: '6.8571rem',
      loadingMinWidth: '8.4286rem',
      maxWidth: '20rem',
      borderRadius: '2px',
      contentFontSize: '1rem',
      contentFontWeight: 600,
      contentLineHeight: 1.4286,
      color: '#252423',
      colorHover: '#252423',
      colorFocus: '#252423',
      colorDisabled: '#605E5C',
      backgroundColor: '#fff',
      backgroundColorActive: '#E1DFDD',
      backgroundColorHover: '#FAF9F8',
      backgroundColorFocus: '#E1DFDD',
      backgroundColorDisabled: '#EDEBE9',
      borderColor: '#E1DFDD',
      borderColorHover: '#C8C6C4',
      borderColorDisabled: 'transparent',
      primaryColor: '#fff',
      primaryColorHover: '#fff',
      primaryColorFocus: '#fff',
      primaryBackgroundColor: '#6264A7',
      primaryBackgroundColorActive: '#33344A',
      primaryBackgroundColorHover: '#464775',
      primaryBackgroundColorFocus: '#464775',
      primaryBorderColor: 'transparent',
      circularBorderRadius: '71.3571rem',
      circularColor: '#484644',
      circularColorActive: '#fff',
      circularBackgroundColor: 'transparent',
      circularBackgroundColorActive: '#484644',
      circularBackgroundColorHover: '#605E5C',
      circularBackgroundColorFocus: '#605E5C',
      circularBorderColor: '#484644',
      circularBorderColorHover: 'transparent',
      circularBorderColorFocus: 'transparent',
      textColor: '#C8C6C4',
      textColorHover: '#A6A7DC',
      textPrimaryColor: '#A6A7DC',
      textPrimaryColorHover: '#A6A7DC',
      textColorDisabled: '#605E5C',
      boxShadow: '0 .2rem .4rem -.075rem rgba(0, 0, 0, .25)',
      loaderBorderSize: '0.1429rem',
      loaderSize: '1.4286rem',
      loaderSvgHeight: '87.1429rem',
      loaderSvgAnimationHeight: '-85.7143rem',
      sizeSmallContentFontSize: '0.8571rem',
      sizeSmallContentLineHeight: 1.3333,
      sizeSmallHeight: '1.7143rem',
      sizeSmallMinWidth: '5.1429rem',
      sizeSmallPadding: '0 0.5714rem',
      sizeSmallLoaderBorderSize: '0.1429rem',
      sizeSmallLoaderSize: '1.0714rem',
      sizeSmallLoaderSvgHeight: '63.9286rem',
      sizeSmallLoaderSvgAnimationHeight: '-62.8571rem',
    },
    {
      color: '#fff',
      colorHover: '#fff',
      colorFocus: '#fff',
      backgroundColor: 'transparent',
      backgroundColorHover: '#292828',
      backgroundColorFocus: '#484644',
      backgroundColorActive: '#484644',
      backgroundColorDisabled: '#3B3A39',
      borderColor: '#484644',
      borderColorHover: '#605E5C',
      primaryBackgroundColorActive: '#8B8CC7',
      primaryBackgroundColorHover: '#8B8CC7',
      primaryBackgroundColorFocus: '#464775',
      circularColor: '#C8C6C4',
      circularColorActive: '#201F1F',
      circularBackgroundColorActive: '#C8C6C4',
      circularBackgroundColorHover: '#B3B0AD',
      circularBackgroundColorFocus: '#C8C6C4',
      circularBorderColor: '#C8C6C4',
    },
    {
      color: '#A72037',
    },
  ],
  componentStyles: {
    root: [
      {
        height: '2.2857rem',
        minWidth: '6.8571rem',
        maxWidth: '20rem',
        color: '#A72037',
        backgroundColor: 'transparent',
        borderRadius: '2px',
        display: 'inline-flex',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
        padding: '0 1.4286rem',
        verticalAlign: 'middle',
        cursor: 'pointer',
        outline: 0,
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: '#484644',
        boxShadow: '0 .2rem .4rem -.075rem rgba(0, 0, 0, .25)',
        ':hover': {
          color: '#fff',
          backgroundColor: '#292828',
          borderColor: '#605E5C',
        },
        ':focus': {
          outline: 0,
          boxShadow: 'none',
          ':active': {
            backgroundColor: '#484644',
          },
        },
        ':focus-visible': {
          borderColor: 'transparent',
          ':before': {
            content: '""',
            position: 'absolute',
            borderStyle: 'solid',
            pointerEvents: 'none',
            top: '0',
            right: '0',
            bottom: '0',
            left: '0',
            borderColor: '#000',
            borderWidth: '1px',
            borderRadius: '2px',
          },
          ':after': {
            content: '""',
            position: 'absolute',
            borderStyle: 'solid',
            pointerEvents: 'none',
            top: '-1px',
            right: '-1px',
            bottom: '-1px',
            left: '-1px',
            borderColor: '#fff',
            borderWidth: '1px',
            borderRadius: '2px',
          },
          color: '#fff',
          backgroundColor: '#484644',
        },
      },
      {
        outline: '5px solid red',
      },
      {
        height: '2.2857rem',
        minWidth: '6.8571rem',
        maxWidth: '20rem',
        color: '#A72037',
        backgroundColor: 'transparent',
        borderRadius: '2px',
        display: 'inline-flex',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
        padding: '0 1.4286rem',
        verticalAlign: 'middle',
        cursor: 'pointer',
        outline: 0,
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: '#484644',
        boxShadow: '0 .2rem .4rem -.075rem rgba(0, 0, 0, .25)',
        ':hover': {
          color: '#fff',
          backgroundColor: '#292828',
          borderColor: '#605E5C',
        },
        ':focus': {
          outline: 0,
          boxShadow: 'none',
          ':active': {
            backgroundColor: '#484644',
          },
        },
        ':focus-visible': {
          borderColor: 'transparent',
          ':before': {
            content: '""',
            position: 'absolute',
            borderStyle: 'solid',
            pointerEvents: 'none',
            top: '0',
            right: '0',
            bottom: '0',
            left: '0',
            borderColor: '#000',
            borderWidth: '1px',
            borderRadius: '2px',
          },
          ':after': {
            content: '""',
            position: 'absolute',
            borderStyle: 'solid',
            pointerEvents: 'none',
            top: '-1px',
            right: '-1px',
            bottom: '-1px',
            left: '-1px',
            borderColor: '#fff',
            borderWidth: '1px',
            borderRadius: '2px',
          },
          color: '#fff',
          backgroundColor: '#484644',
        },
      },
      {
        margin: '1px',
      },
      {
        color: 'blue',
      },
      {},
    ],
    content: [
      {
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        fontSize: '1rem',
        fontWeight: 600,
        lineHeight: 1.4286,
      },
      {
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap',
        fontSize: '1rem',
        fontWeight: 600,
        lineHeight: 1.4286,
      },
    ],
    icon: [{}, {}],
    loader: [
      {
        '& .ui-loader__indicator': {
          width: '1.4286rem',
          height: '1.4286rem',
        },
        '& .ui-loader__svg': {
          ':before': {
            animationName: {
              to: {
                transform: 'translate3d(0, -85.7143rem, 0)',
              },
            },
            borderWidth: '0.1429rem',
            width: '1.4286rem',
            height: '87.1429rem',
          },
        },
        marginRight: '0.2857rem',
      },
      {
        '& .ui-loader__indicator': {
          width: '1.4286rem',
          height: '1.4286rem',
        },
        '& .ui-loader__svg': {
          ':before': {
            animationName: {
              to: {
                transform: 'translate3d(0, -85.7143rem, 0)',
              },
            },
            borderWidth: '0.1429rem',
            width: '1.4286rem',
            height: '87.1429rem',
          },
        },
        marginRight: '0.2857rem',
      },
    ],
  },
}

export default debugData
