const fontAwesomeIcons = new Map([
  // Deprecated *In/Out Naming Conflict)
  ['linkedin in', 'f0e1'],
  ['zoom in', 'f00e'],
  ['zoom out', 'f010'],
  ['sign in', 'f2f6'],
  ['in cart', 'f218'],
  ['log out', 'f2f5'],
  ['sign out', 'f2f5'],

  // Icons
  ['500px', 'f26e'],
  ['accessible icon', 'f368'],
  ['accusoft', 'f369'],
  ['address book', 'f2b9'],
  ['address card', 'f2bb'],
  ['adjust', 'f042'],
  ['adn', 'f170'],
  ['adversal', 'f36a'],
  ['affiliatetheme', 'f36b'],
  ['algolia', 'f36c'],
  ['align center', 'f037'],
  ['align justify', 'f039'],
  ['align left', 'f036'],
  ['align right', 'f038'],
  ['amazon', 'f270'],
  ['amazon pay', 'f42c'],
  ['ambulance', 'f0f9'],
  ['american sign language interpreting', 'f2a3'],
  ['amilia', 'f36d'],
  ['anchor', 'f13d'],
  ['android', 'f17b'],
  ['angellist', 'f209'],
  ['angle double down', 'f103'],
  ['angle double left', 'f100'],
  ['angle double right', 'f101'],
  ['angle double up', 'f102'],
  ['angle down', 'f107'],
  ['angle left', 'f104'],
  ['angle right', 'f105'],
  ['angle up', 'f106'],
  ['angrycreative', 'f36e'],
  ['angular', 'f420'],
  ['app store', 'f36f'],
  ['app store ios', 'f370'],
  ['apper', 'f371'],
  ['apple', 'f179'],
  ['apple pay', 'f415'],
  ['archive', 'f187'],
  ['arrow alternate circle down', 'f358'],
  ['arrow alternate circle left', 'f359'],
  ['arrow alternate circle right', 'f35a'],
  ['arrow alternate circle up', 'f35b'],
  ['arrow circle down', 'f0ab'],
  ['arrow circle left', 'f0a8'],
  ['arrow circle right', 'f0a9'],
  ['arrow circle up', 'f0aa'],
  ['arrow down', 'f063'],
  ['arrow left', 'f060'],
  ['arrow right', 'f061'],
  ['arrow up', 'f062'],
  ['arrows alternate', 'f0b2'],
  ['arrows alternate horizontal', 'f337'],
  ['arrows alternate vertical', 'f338'],
  ['assistive listening systems', 'f2a2'],
  ['asterisk', 'f069'],
  ['asymmetrik', 'f372'],
  ['at', 'f1fa'],
  ['audible', 'f373'],
  ['audio description', 'f29e'],
  ['autoprefixer', 'f41c'],
  ['avianex', 'f374'],
  ['aviato', 'f421'],
  ['aws', 'f375'],
  ['backward', 'f04a'],
  ['balance scale', 'f24e'],
  ['ban', 'f05e'],
  ['band aid', 'f462'],
  ['bandcamp', 'f2d5'],
  ['barcode', 'f02a'],
  ['bars', 'f0c9'],
  ['baseball ball', 'f433'],
  ['basketball ball', 'f434'],
  ['bath', 'f2cd'],
  ['battery empty', 'f244'],
  ['battery full', 'f240'],
  ['battery half', 'f242'],
  ['battery quarter', 'f243'],
  ['battery three quarters', 'f241'],
  ['bed', 'f236'],
  ['beer', 'f0fc'],
  ['behance', 'f1b4'],
  ['behance square', 'f1b5'],
  ['bell', 'f0f3'],
  ['bell slash', 'f1f6'],
  ['bicycle', 'f206'],
  ['bimobject', 'f378'],
  ['binoculars', 'f1e5'],
  ['birthday cake', 'f1fd'],
  ['bitbucket', 'f171'],
  ['bitcoin', 'f379'],
  ['bity', 'f37a'],
  ['black tie', 'f27e'],
  ['blackberry', 'f37b'],
  ['blind', 'f29d'],
  ['blogger', 'f37c'],
  ['blogger b', 'f37d'],
  ['bluetooth', 'f293'],
  ['bluetooth b', 'f294'],
  ['bold', 'f032'],
  ['bolt', 'f0e7'],
  ['bomb', 'f1e2'],
  ['book', 'f02d'],
  ['bookmark', 'f02e'],
  ['bowling ball', 'f436'],
  ['box', 'f466'],
  ['boxes', 'f468'],
  ['braille', 'f2a1'],
  ['briefcase', 'f0b1'],
  ['btc', 'f15a'],
  ['bug', 'f188'],
  ['building', 'f1ad'],
  ['bullhorn', 'f0a1'],
  ['bullseye', 'f140'],
  ['buromobelexperte', 'f37f'],
  ['bus', 'f207'],
  ['buysellads', 'f20d'],
  ['calculator', 'f1ec'],
  ['calendar', 'f133'],
  ['calendar alternate', 'f073'],
  ['calendar check', 'f274'],
  ['calendar minus', 'f272'],
  ['calendar plus', 'f271'],
  ['calendar times', 'f273'],
  ['camera', 'f030'],
  ['camera retro', 'f083'],
  ['car', 'f1b9'],
  ['caret down', 'f0d7'],
  ['caret left', 'f0d9'],
  ['caret right', 'f0da'],
  ['caret square down', 'f150'],
  ['caret square left', 'f191'],
  ['caret square right', 'f152'],
  ['caret square up', 'f151'],
  ['caret up', 'f0d8'],
  ['cart arrow down', 'f218'],
  ['cart plus', 'f217'],
  ['cc amazon pay', 'f42d'],
  ['cc amex', 'f1f3'],
  ['cc apple pay', 'f416'],
  ['cc diners club', 'f24c'],
  ['cc discover', 'f1f2'],
  ['cc jcb', 'f24b'],
  ['cc mastercard', 'f1f1'],
  ['cc paypal', 'f1f4'],
  ['cc stripe', 'f1f5'],
  ['cc visa', 'f1f0'],
  ['centercode', 'f380'],
  ['certificate', 'f0a3'],
  ['chart area', 'f1fe'],
  ['chart bar', 'f080'],
  ['chart line', 'f201'],
  ['chart pie', 'f200'],
  ['check', 'f00c'],
  ['check circle', 'f058'],
  ['check square', 'f14a'],
  ['chess', 'f439'],
  ['chess bishop', 'f43a'],
  ['chess board', 'f43c'],
  ['chess king', 'f43f'],
  ['chess knight', 'f441'],
  ['chess pawn', 'f443'],
  ['chess queen', 'f445'],
  ['chess rook', 'f447'],
  ['chevron circle down', 'f13a'],
  ['chevron circle left', 'f137'],
  ['chevron circle right', 'f138'],
  ['chevron circle up', 'f139'],
  ['chevron down', 'f078'],
  ['chevron left', 'f053'],
  ['chevron right', 'f054'],
  ['chevron up', 'f077'],
  ['child', 'f1ae'],
  ['chrome', 'f268'],
  ['circle', 'f111'],
  ['circle notch', 'f1ce'],
  ['clipboard', 'f328'],
  ['clipboard check', 'f46c'],
  ['clipboard list', 'f46d'],
  ['clock', 'f017'],
  ['clone', 'f24d'],
  ['closed captioning', 'f20a'],
  ['cloud', 'f0c2'],
  ['cloudscale', 'f383'],
  ['cloudsmith', 'f384'],
  ['cloudversify', 'f385'],
  ['code', 'f121'],
  ['code branch', 'f126'],
  ['codepen', 'f1cb'],
  ['codiepie', 'f284'],
  ['coffee', 'f0f4'],
  ['cog', 'f013'],
  ['cogs', 'f085'],
  ['columns', 'f0db'],
  ['comment', 'f075'],
  ['comment alternate', 'f27a'],
  ['comments', 'f086'],
  ['compass', 'f14e'],
  ['compress', 'f066'],
  ['connectdevelop', 'f20e'],
  ['contao', 'f26d'],
  ['copy', 'f0c5'],
  ['copyright', 'f1f9'],
  ['cpanel', 'f388'],
  ['creative commons', 'f25e'],
  ['credit card', 'f09d'],
  ['crop', 'f125'],
  ['crosshairs', 'f05b'],
  ['css3', 'f13c'],
  ['css3 alternate', 'f38b'],
  ['cube', 'f1b2'],
  ['cubes', 'f1b3'],
  ['cut', 'f0c4'],
  ['cuttlefish', 'f38c'],
  ['d and d', 'f38d'],
  ['dashcube', 'f210'],
  ['database', 'f1c0'],
  ['deaf', 'f2a4'],
  ['delicious', 'f1a5'],
  ['deploydog', 'f38e'],
  ['deskpro', 'f38f'],
  ['desktop', 'f108'],
  ['deviantart', 'f1bd'],
  ['digg', 'f1a6'],
  ['digital ocean', 'f391'],
  ['discord', 'f392'],
  ['discourse', 'f393'],
  ['dna', 'f471'],
  ['dochub', 'f394'],
  ['docker', 'f395'],
  ['dollar sign', 'f155'],
  ['dolly', 'f472'],
  ['dolly flatbed', 'f474'],
  ['dot circle', 'f192'],
  ['download', 'f019'],
  ['draft2digital', 'f396'],
  ['dribbble', 'f17d'],
  ['dribbble square', 'f397'],
  ['dropbox', 'f16b'],
  ['drupal', 'f1a9'],
  ['dyalog', 'f399'],
  ['earlybirds', 'f39a'],
  ['edge', 'f282'],
  ['edit', 'f044'],
  ['eject', 'f052'],
  ['elementor', 'f430'],
  ['ellipsis horizontal', 'f141'],
  ['ellipsis vertical', 'f142'],
  ['ember', 'f423'],
  ['empire', 'f1d1'],
  ['envelope', 'f0e0'],
  ['envelope open', 'f2b6'],
  ['envelope square', 'f199'],
  ['envira', 'f299'],
  ['eraser', 'f12d'],
  ['erlang', 'f39d'],
  ['ethereum', 'f42e'],
  ['etsy', 'f2d7'],
  ['euro sign', 'f153'],
  ['exchange alternate', 'f362'],
  ['exclamation', 'f12a'],
  ['exclamation circle', 'f06a'],
  ['exclamation triangle', 'f071'],
  ['expand', 'f065'],
  ['expand arrows alternate', 'f31e'],
  ['expeditedssl', 'f23e'],
  ['external alternate', 'f35d'],
  ['external square alternate', 'f360'],
  ['eye', 'f06e'],
  ['eye dropper', 'f1fb'],
  ['eye slash', 'f070'],
  ['facebook', 'f09a'],
  ['facebook f', 'f39e'],
  ['facebook messenger', 'f39f'],
  ['facebook square', 'f082'],
  ['fast backward', 'f049'],
  ['fast forward', 'f050'],
  ['fax', 'f1ac'],
  ['female', 'f182'],
  ['fighter jet', 'f0fb'],
  ['file', 'f15b'],
  ['file alternate', 'f15c'],
  ['file archive', 'f1c6'],
  ['file audio', 'f1c7'],
  ['file code', 'f1c9'],
  ['file excel', 'f1c3'],
  ['file image', 'f1c5'],
  ['file pdf', 'f1c1'],
  ['file powerpoint', 'f1c4'],
  ['file video', 'f1c8'],
  ['file word', 'f1c2'],
  ['film', 'f008'],
  ['filter', 'f0b0'],
  ['fire', 'f06d'],
  ['fire extinguisher', 'f134'],
  ['firefox', 'f269'],
  ['first aid', 'f479'],
  ['first order', 'f2b0'],
  ['firstdraft', 'f3a1'],
  ['flag', 'f024'],
  ['flag checkered', 'f11e'],
  ['flask', 'f0c3'],
  ['flickr', 'f16e'],
  ['flipboard', 'f44d'],
  ['fly', 'f417'],
  ['folder', 'f07b'],
  ['folder open', 'f07c'],
  ['font', 'f031'],
  ['font awesome', 'f2b4'],
  ['font awesome alternate', 'f35c'],
  ['font awesome flag', 'f425'],
  ['fonticons', 'f280'],
  ['fonticons fi', 'f3a2'],
  ['football ball', 'f44e'],
  ['fort awesome', 'f286'],
  ['fort awesome alternate', 'f3a3'],
  ['forumbee', 'f211'],
  ['forward', 'f04e'],
  ['foursquare', 'f180'],
  ['free code camp', 'f2c5'],
  ['freebsd', 'f3a4'],
  ['frown', 'f119'],
  ['futbol', 'f1e3'],
  ['gamepad', 'f11b'],
  ['gavel', 'f0e3'],
  ['gem', 'f3a5'],
  ['genderless', 'f22d'],
  ['get pocket', 'f265'],
  ['gg', 'f260'],
  ['gg circle', 'f261'],
  ['gift', 'f06b'],
  ['git', 'f1d3'],
  ['git square', 'f1d2'],
  ['github', 'f09b'],
  ['github alternate', 'f113'],
  ['github square', 'f092'],
  ['gitkraken', 'f3a6'],
  ['gitlab', 'f296'],
  ['gitter', 'f426'],
  ['glass martini', 'f000'],
  ['glide', 'f2a5'],
  ['glide g', 'f2a6'],
  ['globe', 'f0ac'],
  ['gofore', 'f3a7'],
  ['golf ball', 'f450'],
  ['goodreads', 'f3a8'],
  ['goodreads g', 'f3a9'],
  ['google', 'f1a0'],
  ['google drive', 'f3aa'],
  ['google play', 'f3ab'],
  ['google plus', 'f2b3'],
  ['google plus g', 'f0d5'],
  ['google plus square', 'f0d4'],
  ['google wallet', 'f1ee'],
  ['graduation cap', 'f19d'],
  ['gratipay', 'f184'],
  ['grav', 'f2d6'],
  ['gripfire', 'f3ac'],
  ['grunt', 'f3ad'],
  ['gulp', 'f3ae'],
  ['h square', 'f0fd'],
  ['hacker news', 'f1d4'],
  ['hacker news square', 'f3af'],
  ['hand lizard', 'f258'],
  ['hand paper', 'f256'],
  ['hand peace', 'f25b'],
  ['hand point down', 'f0a7'],
  ['hand point left', 'f0a5'],
  ['hand point right', 'f0a4'],
  ['hand point up', 'f0a6'],
  ['hand pointer', 'f25a'],
  ['hand rock', 'f255'],
  ['hand scissors', 'f257'],
  ['hand spock', 'f259'],
  ['handshake', 'f2b5'],
  ['hashtag', 'f292'],
  ['hdd', 'f0a0'],
  ['heading', 'f1dc'],
  ['headphones', 'f025'],
  ['heart', 'f004'],
  ['heartbeat', 'f21e'],
  ['hips', 'f452'],
  ['hire a helper', 'f3b0'],
  ['history', 'f1da'],
  ['hockey puck', 'f453'],
  ['home', 'f015'],
  ['hooli', 'f427'],
  ['hospital', 'f0f8'],
  ['hospital symbol', 'f47e'],
  ['hotjar', 'f3b1'],
  ['hourglass', 'f254'],
  ['hourglass end', 'f253'],
  ['hourglass half', 'f252'],
  ['hourglass start', 'f251'],
  ['houzz', 'f27c'],
  ['html5', 'f13b'],
  ['hubspot', 'f3b2'],
  ['i cursor', 'f246'],
  ['id badge', 'f2c1'],
  ['id card', 'f2c2'],
  ['image', 'f03e'],
  ['images', 'f302'],
  ['imdb', 'f2d8'],
  ['inbox', 'f01c'],
  ['indent', 'f03c'],
  ['industry', 'f275'],
  ['info', 'f129'],
  ['info circle', 'f05a'],
  ['instagram', 'f16d'],
  ['internet explorer', 'f26b'],
  ['ioxhost', 'f208'],
  ['italic', 'f033'],
  ['itunes', 'f3b4'],
  ['itunes note', 'f3b5'],
  ['jenkins', 'f3b6'],
  ['joget', 'f3b7'],
  ['joomla', 'f1aa'],
  ['js', 'f3b8'],
  ['js square', 'f3b9'],
  ['jsfiddle', 'f1cc'],
  ['key', 'f084'],
  ['keyboard', 'f11c'],
  ['keycdn', 'f3ba'],
  ['kickstarter', 'f3bb'],
  ['kickstarter k', 'f3bc'],
  ['korvue', 'f42f'],
  ['language', 'f1ab'],
  ['laptop', 'f109'],
  ['laravel', 'f3bd'],
  ['lastfm', 'f202'],
  ['lastfm square', 'f203'],
  ['leaf', 'f06c'],
  ['leanpub', 'f212'],
  ['lemon', 'f094'],
  ['less', 'f41d'],
  ['level down alternate', 'f3be'],
  ['level up alternate', 'f3bf'],
  ['life ring', 'f1cd'],
  ['lightbulb', 'f0eb'],
  ['linechat', 'f3c0'],
  ['linkify', 'f0c1'],
  ['linkedin', 'f08c'],
  ['linkedin alt', 'f0e1'],
  ['linode', 'f2b8'],
  ['linux', 'f17c'],
  ['lira sign', 'f195'],
  ['list', 'f03a'],
  ['list alternate', 'f022'],
  ['list ol', 'f0cb'],
  ['list ul', 'f0ca'],
  ['location arrow', 'f124'],
  ['lock', 'f023'],
  ['lock open', 'f3c1'],
  ['long arrow alternate down', 'f309'],
  ['long arrow alternate left', 'f30a'],
  ['long arrow alternate right', 'f30b'],
  ['long arrow alternate up', 'f30c'],
  ['low vision', 'f2a8'],
  ['lyft', 'f3c3'],
  ['magento', 'f3c4'],
  ['magic', 'f0d0'],
  ['magnet', 'f076'],
  ['male', 'f183'],
  ['map', 'f279'],
  ['map marker', 'f041'],
  ['map marker alternate', 'f3c5'],
  ['map pin', 'f276'],
  ['map signs', 'f277'],
  ['mars', 'f222'],
  ['mars double', 'f227'],
  ['mars stroke', 'f229'],
  ['mars stroke horizontal', 'f22b'],
  ['mars stroke vertical', 'f22a'],
  ['maxcdn', 'f136'],
  ['medapps', 'f3c6'],
  ['medium', 'f23a'],
  ['medium m', 'f3c7'],
  ['medkit', 'f0fa'],
  ['medrt', 'f3c8'],
  ['meetup', 'f2e0'],
  ['meh', 'f11a'],
  ['mercury', 'f223'],
  ['microchip', 'f2db'],
  ['microphone', 'f130'],
  ['microphone slash', 'f131'],
  ['microsoft', 'f3ca'],
  ['minus', 'f068'],
  ['minus circle', 'f056'],
  ['minus square', 'f146'],
  ['mix', 'f3cb'],
  ['mixcloud', 'f289'],
  ['mizuni', 'f3cc'],
  ['mobile', 'f10b'],
  ['mobile alternate', 'f3cd'],
  ['modx', 'f285'],
  ['monero', 'f3d0'],
  ['money bill alternate', 'f3d1'],
  ['moon', 'f186'],
  ['motorcycle', 'f21c'],
  ['mouse pointer', 'f245'],
  ['music', 'f001'],
  ['napster', 'f3d2'],
  ['neuter', 'f22c'],
  ['newspaper', 'f1ea'],
  ['nintendo switch', 'f418'],
  ['node', 'f419'],
  ['node js', 'f3d3'],
  ['npm', 'f3d4'],
  ['ns8', 'f3d5'],
  ['nutritionix', 'f3d6'],
  ['object group', 'f247'],
  ['object ungroup', 'f248'],
  ['odnoklassniki', 'f263'],
  ['odnoklassniki square', 'f264'],
  ['opencart', 'f23d'],
  ['openid', 'f19b'],
  ['opera', 'f26a'],
  ['optin monster', 'f23c'],
  ['osi', 'f41a'],
  ['outdent', 'f03b'],
  ['page4', 'f3d7'],
  ['pagelines', 'f18c'],
  ['paint brush', 'f1fc'],
  ['palfed', 'f3d8'],
  ['pallet', 'f482'],
  ['paper plane', 'f1d8'],
  ['paperclip', 'f0c6'],
  ['paragraph', 'f1dd'],
  ['paste', 'f0ea'],
  ['patreon', 'f3d9'],
  ['pause', 'f04c'],
  ['pause circle', 'f28b'],
  ['paw', 'f1b0'],
  ['paypal', 'f1ed'],
  ['pen square', 'f14b'],
  ['pencil alternate', 'f303'],
  ['percent', 'f295'],
  ['periscope', 'f3da'],
  ['phabricator', 'f3db'],
  ['phoenix framework', 'f3dc'],
  ['phone', 'f095'],
  ['phone square', 'f098'],
  ['phone volume', 'f2a0'],
  ['php', 'f457'],
  ['pied piper', 'f2ae'],
  ['pied piper alternate', 'f1a8'],
  ['pied piper pp', 'f1a7'],
  ['pills', 'f484'],
  ['pinterest', 'f0d2'],
  ['pinterest p', 'f231'],
  ['pinterest square', 'f0d3'],
  ['plane', 'f072'],
  ['play', 'f04b'],
  ['play circle', 'f144'],
  ['playstation', 'f3df'],
  ['plug', 'f1e6'],
  ['plus', 'f067'],
  ['plus circle', 'f055'],
  ['plus square', 'f0fe'],
  ['podcast', 'f2ce'],
  ['pound sign', 'f154'],
  ['power off', 'f011'],
  ['print', 'f02f'],
  ['product hunt', 'f288'],
  ['pushed', 'f3e1'],
  ['puzzle piece', 'f12e'],
  ['python', 'f3e2'],
  ['qq', 'f1d6'],
  ['qrcode', 'f029'],
  ['question', 'f128'],
  ['question circle', 'f059'],
  ['quidditch', 'f458'],
  ['quinscape', 'f459'],
  ['quora', 'f2c4'],
  ['quote left', 'f10d'],
  ['quote right', 'f10e'],
  ['random', 'f074'],
  ['ravelry', 'f2d9'],
  ['react', 'f41b'],
  ['rebel', 'f1d0'],
  ['recycle', 'f1b8'],
  ['redriver', 'f3e3'],
  ['reddit', 'f1a1'],
  ['reddit alien', 'f281'],
  ['reddit square', 'f1a2'],
  ['redo', 'f01e'],
  ['redo alternate', 'f2f9'],
  ['registered', 'f25d'],
  ['rendact', 'f3e4'],
  ['renren', 'f18b'],
  ['reply', 'f3e5'],
  ['reply all', 'f122'],
  ['replyd', 'f3e6'],
  ['resolving', 'f3e7'],
  ['retweet', 'f079'],
  ['road', 'f018'],
  ['rocket', 'f135'],
  ['rocketchat', 'f3e8'],
  ['rockrms', 'f3e9'],
  ['rss', 'f09e'],
  ['rss square', 'f143'],
  ['ruble sign', 'f158'],
  ['rupee sign', 'f156'],
  ['safari', 'f267'],
  ['sass', 'f41e'],
  ['save', 'f0c7'],
  ['schlix', 'f3ea'],
  ['scribd', 'f28a'],
  ['search', 'f002'],
  ['search minus', 'f010'],
  ['search plus', 'f00e'],
  ['searchengin', 'f3eb'],
  ['sellcast', 'f2da'],
  ['sellsy', 'f213'],
  ['server', 'f233'],
  ['servicestack', 'f3ec'],
  ['share', 'f064'],
  ['share alternate', 'f1e0'],
  ['share alternate square', 'f1e1'],
  ['share square', 'f14d'],
  ['shekel sign', 'f20b'],
  ['shield alternate', 'f3ed'],
  ['ship', 'f21a'],
  ['shipping fast', 'f48b'],
  ['shirtsinbulk', 'f214'],
  ['shopping bag', 'f290'],
  ['shopping basket', 'f291'],
  ['shopping cart', 'f07a'],
  ['shower', 'f2cc'],
  ['sign language', 'f2a7'],
  ['signal', 'f012'],
  ['simplybuilt', 'f215'],
  ['sistrix', 'f3ee'],
  ['sitemap', 'f0e8'],
  ['skyatlas', 'f216'],
  ['skype', 'f17e'],
  ['slack', 'f198'],
  ['slack hash', 'f3ef'],
  ['sliders horizontal', 'f1de'],
  ['slideshare', 'f1e7'],
  ['smile', 'f118'],
  ['snapchat', 'f2ab'],
  ['snapchat ghost', 'f2ac'],
  ['snapchat square', 'f2ad'],
  ['snowflake', 'f2dc'],
  ['sort', 'f0dc'],
  ['sort alphabet down', 'f15d'],
  ['sort alphabet up', 'f15e'],
  ['sort amount down', 'f160'],
  ['sort amount up', 'f161'],
  ['sort down', 'f0dd'],
  ['sort numeric down', 'f162'],
  ['sort numeric up', 'f163'],
  ['sort up', 'f0de'],
  ['soundcloud', 'f1be'],
  ['space shuttle', 'f197'],
  ['speakap', 'f3f3'],
  ['spinner', 'f110'],
  ['spotify', 'f1bc'],
  ['square', 'f0c8'],
  ['square full', 'f45c'],
  ['stack exchange', 'f18d'],
  ['stack overflow', 'f16c'],
  ['star', 'f005'],
  ['star half', 'f089'],
  ['staylinked', 'f3f5'],
  ['steam', 'f1b6'],
  ['steam square', 'f1b7'],
  ['steam symbol', 'f3f6'],
  ['step backward', 'f048'],
  ['step forward', 'f051'],
  ['stethoscope', 'f0f1'],
  ['sticker mule', 'f3f7'],
  ['sticky note', 'f249'],
  ['stop', 'f04d'],
  ['stop circle', 'f28d'],
  ['stopwatch', 'f2f2'],
  ['strava', 'f428'],
  ['street view', 'f21d'],
  ['strikethrough', 'f0cc'],
  ['stripe', 'f429'],
  ['stripe s', 'f42a'],
  ['studiovinari', 'f3f8'],
  ['stumbleupon', 'f1a4'],
  ['stumbleupon circle', 'f1a3'],
  ['subscript', 'f12c'],
  ['subway', 'f239'],
  ['suitcase', 'f0f2'],
  ['sun', 'f185'],
  ['superpowers', 'f2dd'],
  ['superscript', 'f12b'],
  ['supple', 'f3f9'],
  ['sync', 'f021'],
  ['sync alternate', 'f2f1'],
  ['syringe', 'f48e'],
  ['table', 'f0ce'],
  ['table tennis', 'f45d'],
  ['tablet', 'f10a'],
  ['tablet alternate', 'f3fa'],
  ['tachometer alternate', 'f3fd'],
  ['tag', 'f02b'],
  ['tags', 'f02c'],
  ['tasks', 'f0ae'],
  ['taxi', 'f1ba'],
  ['telegram', 'f2c6'],
  ['telegram plane', 'f3fe'],
  ['tencent weibo', 'f1d5'],
  ['terminal', 'f120'],
  ['text height', 'f034'],
  ['text width', 'f035'],
  ['th', 'f00a'],
  ['th large', 'f009'],
  ['th list', 'f00b'],
  ['themeisle', 'f2b2'],
  ['thermometer', 'f491'],
  ['thermometer empty', 'f2cb'],
  ['thermometer full', 'f2c7'],
  ['thermometer half', 'f2c9'],
  ['thermometer quarter', 'f2ca'],
  ['thermometer three quarters', 'f2c8'],
  ['thumbs down', 'f165'],
  ['thumbs up', 'f164'],
  ['thumbtack', 'f08d'],
  ['ticket alternate', 'f3ff'],
  ['times', 'f00d'],
  ['times circle', 'f057'],
  ['tint', 'f043'],
  ['toggle off', 'f204'],
  ['toggle on', 'f205'],
  ['trademark', 'f25c'],
  ['train', 'f238'],
  ['transgender', 'f224'],
  ['transgender alternate', 'f225'],
  ['trash', 'f1f8'],
  ['trash alternate', 'f2ed'],
  ['tree', 'f1bb'],
  ['trello', 'f181'],
  ['tripadvisor', 'f262'],
  ['trophy', 'f091'],
  ['truck', 'f0d1'],
  ['tty', 'f1e4'],
  ['tumblr', 'f173'],
  ['tumblr square', 'f174'],
  ['tv', 'f26c'],
  ['twitch', 'f1e8'],
  ['twitter', 'f099'],
  ['twitter square', 'f081'],
  ['typo3', 'f42b'],
  ['uber', 'f402'],
  ['uikit', 'f403'],
  ['umbrella', 'f0e9'],
  ['underline', 'f0cd'],
  ['undo', 'f0e2'],
  ['undo alternate', 'f2ea'],
  ['uniregistry', 'f404'],
  ['universal access', 'f29a'],
  ['university', 'f19c'],
  ['unlink', 'f127'],
  ['unlock', 'f09c'],
  ['unlock alternate', 'f13e'],
  ['untappd', 'f405'],
  ['upload', 'f093'],
  ['usb', 'f287'],
  ['user', 'f007'],
  ['user circle', 'f2bd'],
  ['user md', 'f0f0'],
  ['user plus', 'f234'],
  ['user secret', 'f21b'],
  ['user times', 'f235'],
  ['users', 'f0c0'],
  ['ussunnah', 'f407'],
  ['utensil spoon', 'f2e5'],
  ['utensils', 'f2e7'],
  ['vaadin', 'f408'],
  ['venus', 'f221'],
  ['venus double', 'f226'],
  ['venus mars', 'f228'],
  ['viacoin', 'f237'],
  ['viadeo', 'f2a9'],
  ['viadeo square', 'f2aa'],
  ['viber', 'f409'],
  ['video', 'f03d'],
  ['vimeo', 'f40a'],
  ['vimeo square', 'f194'],
  ['vimeo v', 'f27d'],
  ['vine', 'f1ca'],
  ['vk', 'f189'],
  ['vnv', 'f40b'],
  ['volleyball ball', 'f45f'],
  ['volume down', 'f027'],
  ['volume off', 'f026'],
  ['volume up', 'f028'],
  ['vuejs', 'f41f'],
  ['warehouse', 'f494'],
  ['weibo', 'f18a'],
  ['weight', 'f496'],
  ['weixin', 'f1d7'],
  ['whatsapp', 'f232'],
  ['whatsapp square', 'f40c'],
  ['wheelchair', 'f193'],
  ['whmcs', 'f40d'],
  ['wifi', 'f1eb'],
  ['wikipedia w', 'f266'],
  ['window close', 'f410'],
  ['window maximize', 'f2d0'],
  ['window minimize', 'f2d1'],
  ['window restore', 'f2d2'],
  ['windows', 'f17a'],
  ['won sign', 'f159'],
  ['wordpress', 'f19a'],
  ['wordpress simple', 'f411'],
  ['wpbeginner', 'f297'],
  ['wpexplorer', 'f2de'],
  ['wpforms', 'f298'],
  ['wrench', 'f0ad'],
  ['xbox', 'f412'],
  ['xing', 'f168'],
  ['xing square', 'f169'],
  ['y combinator', 'f23b'],
  ['yahoo', 'f19e'],
  ['yandex', 'f413'],
  ['yandex international', 'f414'],
  ['yelp', 'f1e9'],
  ['yen sign', 'f157'],
  ['yoast', 'f2b1'],
  ['youtube', 'f167'],
  ['youtube square', 'f431'],

  // Aliases
  ['chess rock', 'f447'],
  ['ordered list', 'f0cb'],
  ['unordered list', 'f0ca'],
  ['user doctor', 'f0f0'],
  ['shield', 'f3ed'],
  ['puzzle', 'f12e'],
  ['credit card amazon pay', 'f42d'],
  ['credit card american express', 'f1f3'],
  ['credit card diners club', 'f24c'],
  ['credit card discover', 'f1f2'],
  ['credit card jcb', 'f24b'],
  ['credit card mastercard', 'f1f1'],
  ['credit card paypal', 'f1f4'],
  ['credit card stripe', 'f1f5'],
  ['credit card visa', 'f1f0'],
  ['add circle', 'f055'],
  ['add square', 'f0fe'],
  ['add to calendar', 'f271'],
  ['add to cart', 'f217'],
  ['add user', 'f234'],
  ['add', 'f067'],
  ['alarm mute', 'f1f6'],
  ['alarm', 'f0f3'],
  ['ald', 'f2a2'],
  ['als', 'f2a2'],
  ['american express card', 'f1f3'],
  ['american express', 'f1f3'],
  ['amex', 'f1f3'],
  ['announcement', 'f0a1'],
  ['area chart', 'f1fe'],
  ['area graph', 'f1fe'],
  ['arrow down cart', 'f218'],
  ['asexual', 'f22d'],
  ['asl interpreting', 'f2a3'],
  ['asl', 'f2a3'],
  ['assistive listening devices', 'f2a2'],
  ['attach', 'f0c6'],
  ['attention', 'f06a'],
  ['balance', 'f24e'],
  ['bar', 'f0fc'],
  ['bathtub', 'f2cd'],
  ['battery four', 'f240'],
  ['battery high', 'f241'],
  ['battery low', 'f243'],
  ['battery medium', 'f242'],
  ['battery one', 'f243'],
  ['battery three', 'f241'],
  ['battery two', 'f242'],
  ['battery zero', 'f244'],
  ['birthday', 'f1fd'],
  ['block layout', 'f009'],
  ['bluetooth alternative', 'f294'],
  ['broken chain', 'f127'],
  ['browser', 'f022'],
  ['call square', 'f098'],
  ['call', 'f095'],
  ['cancel', 'f00d'],
  ['cart', 'f07a'],
  ['cc', 'f20a'],
  ['chain', 'f0c1'],
  ['chat', 'f075'],
  ['checked calendar', 'f274'],
  ['checkmark', 'f00c'],
  ['circle notched', 'f1ce'],
  ['close', 'f00d'],
  ['cny', 'f157'],
  ['cocktail', 'f000'],
  ['commenting', 'f27a'],
  ['computer', 'f108'],
  ['configure', 'f0ad'],
  ['content', 'f0c9'],
  ['deafness', 'f2a4'],
  ['delete calendar', 'f273'],
  ['delete', 'f00d'],
  ['detective', 'f21b'],
  ['diners club card', 'f24c'],
  ['diners club', 'f24c'],
  ['discover card', 'f1f2'],
  ['discover', 'f1f2'],
  ['discussions', 'f086'],
  ['doctor', 'f0f0'],
  ['dollar', 'f155'],
  ['dont', 'f05e'],
  ['dribble', 'f17d'],
  ['drivers license', 'f2c2'],
  ['dropdown', 'f0d7'],
  ['eercast', 'f2da'],
  ['emergency', 'f0f9'],
  ['envira gallery', 'f299'],
  ['erase', 'f12d'],
  ['eur', 'f153'],
  ['euro', 'f153'],
  ['eyedropper', 'f1fb'],
  ['fa', 'f2b4'],
  ['factory', 'f275'],
  ['favorite', 'f005'],
  ['feed', 'f09e'],
  ['female homosexual', 'f226'],
  ['file text', 'f15c'],
  ['find', 'f1e5'],
  ['first aid', 'f0fa'],
  ['five hundred pixels', 'f26e'],
  ['fork', 'f126'],
  ['game', 'f11b'],
  ['gay', 'f227'],
  ['gbp', 'f154'],
  ['gittip', 'f184'],
  ['google plus circle', 'f2b3'],
  ['google plus official', 'f2b3'],
  ['grab', 'f255'],
  ['graduation', 'f19d'],
  ['grid layout', 'f00a'],
  ['group', 'f0c0'],
  ['h', 'f0fd'],
  ['hand victory', 'f25b'],
  ['handicap', 'f193'],
  ['hard of hearing', 'f2a4'],
  ['header', 'f1dc'],
  ['help circle', 'f059'],
  ['help', 'f128'],
  ['heterosexual', 'f228'],
  ['hide', 'f070'],
  ['hotel', 'f236'],
  ['hourglass four', 'f254'],
  ['hourglass full', 'f254'],
  ['hourglass one', 'f251'],
  ['hourglass three', 'f253'],
  ['hourglass two', 'f252'],
  ['idea', 'f0eb'],
  ['ils', 'f20b'],
  ['in-cart', 'f218'],
  ['inr', 'f156'],
  ['intergender', 'f224'],
  ['intersex', 'f224'],
  ['japan credit bureau card', 'f24b'],
  ['japan credit bureau', 'f24b'],
  ['jcb', 'f24b'],
  ['jpy', 'f157'],
  ['krw', 'f159'],
  ['lab', 'f0c3'],
  ['law', 'f24e'],
  ['legal', 'f0e3'],
  ['lesbian', 'f226'],
  ['lightning', 'f0e7'],
  ['like', 'f004'],
  ['line graph', 'f201'],
  ['linkedin square', 'f08c'],
  ['linkify', 'f0c1'],
  ['lira', 'f195'],
  ['list layout', 'f00b'],
  ['magnify', 'f00e'],
  ['mail forward', 'f064'],
  ['mail square', 'f199'],
  ['mail', 'f0e0'],
  ['male homosexual', 'f227'],
  ['man', 'f222'],
  ['marker', 'f041'],
  ['mars alternate', 'f229'],
  ['mars horizontal', 'f22b'],
  ['mars vertical', 'f22a'],
  ['mastercard card', 'f1f1'],
  ['mastercard', 'f1f1'],
  ['microsoft edge', 'f282'],
  ['military', 'f0fb'],
  ['ms edge', 'f282'],
  ['mute', 'f131'],
  ['new pied piper', 'f2ae'],
  ['non binary transgender', 'f223'],
  ['numbered list', 'f0cb'],
  ['optinmonster', 'f23c'],
  ['options', 'f1de'],
  ['other gender horizontal', 'f22b'],
  ['other gender vertical', 'f22a'],
  ['other gender', 'f229'],
  ['payment', 'f09d'],
  ['paypal card', 'f1f4'],
  ['pencil square', 'f14b'],
  ['photo', 'f030'],
  ['picture', 'f03e'],
  ['pie chart', 'f200'],
  ['pie graph', 'f200'],
  ['pied piper hat', 'f2ae'],
  ['pin', 'f08d'],
  ['plus cart', 'f217'],
  ['pocket', 'f265'],
  ['point', 'f041'],
  ['pointing down', 'f0a7'],
  ['pointing left', 'f0a5'],
  ['pointing right', 'f0a4'],
  ['pointing up', 'f0a6'],
  ['pound', 'f154'],
  ['power cord', 'f1e6'],
  ['power', 'f011'],
  ['privacy', 'f084'],
  ['r circle', 'f25d'],
  ['rain', 'f0e9'],
  ['record', 'f03d'],
  ['refresh', 'f021'],
  ['remove circle', 'f057'],
  ['remove from calendar', 'f272'],
  ['remove user', 'f235'],
  ['remove', 'f00d'],
  ['repeat', 'f01e'],
  ['rmb', 'f157'],
  ['rouble', 'f158'],
  ['rub', 'f158'],
  ['ruble', 'f158'],
  ['rupee', 'f156'],
  ['s15', 'f2cd'],
  ['selected radio', 'f192'],
  ['send', 'f1d8'],
  ['setting', 'f013'],
  ['settings', 'f085'],
  ['shekel', 'f20b'],
  ['sheqel', 'f20b'],
  ['shipping', 'f0d1'],
  ['shop', 'f07a'],
  ['shuffle', 'f074'],
  ['shutdown', 'f011'],
  ['sidebar', 'f0c9'],
  ['signing', 'f2a7'],
  ['signup', 'f044'],
  ['sliders', 'f1de'],
  ['soccer', 'f1e3'],
  ['sort alphabet ascending', 'f15d'],
  ['sort alphabet descending', 'f15e'],
  ['sort ascending', 'f0de'],
  ['sort content ascending', 'f160'],
  ['sort content descending', 'f161'],
  ['sort descending', 'f0dd'],
  ['sort numeric ascending', 'f162'],
  ['sort numeric descending', 'f163'],
  ['sound', 'f025'],
  ['spy', 'f21b'],
  ['stripe card', 'f1f5'],
  ['student', 'f19d'],
  ['talk', 'f27a'],
  ['target', 'f140'],
  ['teletype', 'f1e4'],
  ['television', 'f26c'],
  ['text cursor', 'f246'],
  ['text telephone', 'f1e4'],
  ['theme isle', 'f2b2'],
  ['theme', 'f043'],
  ['thermometer', 'f2c7'],
  ['thumb tack', 'f08d'],
  ['time', 'f017'],
  ['tm', 'f25c'],
  ['toggle down', 'f150'],
  ['toggle left', 'f191'],
  ['toggle right', 'f152'],
  ['toggle up', 'f151'],
  ['translate', 'f1ab'],
  ['travel', 'f0b1'],
  ['treatment', 'f0f1'],
  ['triangle down', 'f0d7'],
  ['triangle left', 'f0d9'],
  ['triangle right', 'f0da'],
  ['triangle up', 'f0d8'],
  ['try', 'f195'],
  ['unhide', 'f06e'],
  ['unlinkify', 'f127'],
  ['unmute', 'f130'],
  ['usd', 'f155'],
  ['user cancel', 'f235'],
  ['user close', 'f235'],
  ['user delete', 'f235'],
  ['user x', 'f235'],
  ['vcard', 'f2bb'],
  ['video camera', 'f03d'],
  ['video play', 'f144'],
  ['visa card', 'f1f0'],
  ['visa', 'f1f0'],
  ['volume control phone', 'f2a0'],
  ['wait', 'f017'],
  ['warning circle', 'f06a'],
  ['warning sign', 'f071'],
  ['warning', 'f12a'],
  ['wechat', 'f1d7'],
  ['wi-fi', 'f1eb'],
  ['wikipedia', 'f266'],
  ['winner', 'f091'],
  ['wizard', 'f0d0'],
  ['woman', 'f221'],
  ['won', 'f159'],
  ['wordpress beginner', 'f297'],
  ['wordpress forms', 'f298'],
  ['world', 'f0ac'],
  ['write square', 'f14b'],
  ['x', 'f00d'],
  ['yc', 'f23b'],
  ['ycombinator', 'f23b'],
  ['yen', 'f157'],
  ['zip', 'f187'],
  ['zoom-in', 'f00e'],
  ['zoom-out', 'f010'],
  ['zoom', 'f00e'],
  ['bitbucket square', 'f171'],
  ['checkmark box', 'f14a'],
  ['circle thin', 'f111'],
  ['cloud download', 'f381'],
  ['cloud upload', 'f382'],
  ['compose', 'f303'],
  ['conversation', 'f086'],
  ['credit card alternative', 'f09d'],
  ['currency', 'f3d1'],
  ['dashboard', 'f3fd'],
  ['diamond', 'f3a5'],
  ['disk', 'f0a0'],
  ['exchange', 'f362'],
  ['external share', 'f14d'],
  ['external square', 'f360'],
  ['external', 'f35d'],
  ['facebook official', 'f082'],
  ['food', 'f2e7'],
  ['hourglass zero', 'f253'],
  ['level down', 'f3be'],
  ['level up', 'f3bf'],
  ['logout', 'f2f5'],
  ['meanpath', 'f0c8'],
  ['money', 'f3d1'],
  ['move', 'f0b2'],
  ['pencil', 'f303'],
  ['protect', 'f023'],
  ['radio', 'f192'],
  ['remove bookmark', 'f02e'],
  ['resize horizontal', 'f337'],
  ['resize vertical', 'f338'],
  ['sign-in', 'f2f6'],
  ['sign-out', 'f2f5'],
  ['spoon', 'f2e5'],
  ['star half empty', 'f089'],
  ['star half full', 'f089'],
  ['ticket', 'f3ff'],
  ['times rectangle', 'f410'],
  ['write', 'f303'],
  ['youtube play', 'f167'],
  ['address book outline', 'f2b9'],
  ['address card outline', 'f2bb'],
  ['arrow alternate circle down outline', 'f358'],
  ['arrow alternate circle left outline', 'f359'],
  ['arrow alternate circle right outline', 'f35a'],
  ['arrow alternate circle up outline', 'f35b'],
  ['bell outline', 'f0f3'],
  ['bell slash outline', 'f1f6'],
  ['bookmark outline', 'f02e'],
  ['building outline', 'f1ad'],
  ['calendar outline', 'f133'],
  ['calendar alternate outline', 'f073'],
  ['calendar check outline', 'f274'],
  ['calendar minus outline', 'f272'],
  ['calendar plus outline', 'f271'],
  ['calendar times outline', 'f273'],
  ['caret square down outline', 'f150'],
  ['caret square left outline', 'f191'],
  ['caret square right outline', 'f152'],
  ['caret square up outline', 'f151'],
  ['chart bar outline', 'f080'],
  ['check circle outline', 'f058'],
  ['check square outline', 'f14a'],
  ['circle outline', 'f111'],
  ['clipboard outline', 'f328'],
  ['clock outline', 'f017'],
  ['clone outline', 'f24d'],
  ['closed captioning outline', 'f20a'],
  ['comment outline', 'f075'],
  ['comment alternate outline', 'f27a'],
  ['comments outline', 'f086'],
  ['compass outline', 'f14e'],
  ['copy outline', 'f0c5'],
  ['copyright outline', 'f1f9'],
  ['credit card outline', 'f09d'],
  ['dot circle outline', 'f192'],
  ['edit outline', 'f044'],
  ['envelope outline', 'f0e0'],
  ['envelope open outline', 'f2b6'],
  ['eye slash outline', 'f070'],
  ['file outline', 'f15b'],
  ['file alternate outline', 'f15c'],
  ['file archive outline', 'f1c6'],
  ['file audio outline', 'f1c7'],
  ['file code outline', 'f1c9'],
  ['file excel outline', 'f1c3'],
  ['file image outline', 'f1c5'],
  ['file pdf outline', 'f1c1'],
  ['file powerpoint outline', 'f1c4'],
  ['file video outline', 'f1c8'],
  ['file word outline', 'f1c2'],
  ['flag outline', 'f024'],
  ['folder outline', 'f07b'],
  ['folder open outline', 'f07c'],
  ['frown outline', 'f119'],
  ['futbol outline', 'f1e3'],
  ['gem outline', 'f3a5'],
  ['hand lizard outline', 'f258'],
  ['hand paper outline', 'f256'],
  ['hand peace outline', 'f25b'],
  ['hand point down outline', 'f0a7'],
  ['hand point left outline', 'f0a5'],
  ['hand point right outline', 'f0a4'],
  ['hand point up outline', 'f0a6'],
  ['hand pointer outline', 'f25a'],
  ['hand rock outline', 'f255'],
  ['hand scissors outline', 'f257'],
  ['hand spock outline', 'f259'],
  ['handshake outline', 'f2b5'],
  ['hdd outline', 'f0a0'],
  ['heart outline', 'f004'],
  ['hospital outline', 'f0f8'],
  ['hourglass outline', 'f254'],
  ['id badge outline', 'f2c1'],
  ['id card outline', 'f2c2'],
  ['image outline', 'f03e'],
  ['images outline', 'f302'],
  ['keyboard outline', 'f11c'],
  ['lemon outline', 'f094'],
  ['life ring outline', 'f1cd'],
  ['lightbulb outline', 'f0eb'],
  ['list alternate outline', 'f022'],
  ['map outline', 'f279'],
  ['meh outline', 'f11a'],
  ['minus square outline', 'f146'],
  ['money bill alternate outline', 'f3d1'],
  ['moon outline', 'f186'],
  ['newspaper outline', 'f1ea'],
  ['object group outline', 'f247'],
  ['object ungroup outline', 'f248'],
  ['paper plane outline', 'f1d8'],
  ['pause circle outline', 'f28b'],
  ['play circle outline', 'f144'],
  ['plus square outline', 'f0fe'],
  ['question circle outline', 'f059'],
  ['registered outline', 'f25d'],
  ['save outline', 'f0c7'],
  ['share square outline', 'f14d'],
  ['smile outline', 'f118'],
  ['snowflake outline', 'f2dc'],
  ['square outline', 'f0c8'],
  ['star outline', 'f005'],
  ['star half outline', 'f089'],
  ['sticky note outline', 'f249'],
  ['stop circle outline', 'f28d'],
  ['sun outline', 'f185'],
  ['thumbs down outline', 'f165'],
  ['thumbs up outline', 'f164'],
  ['times circle outline', 'f057'],
  ['trash alternate outline', 'f2ed'],
  ['user outline', 'f007'],
  ['user circle outline', 'f2bd'],
  ['window close outline', 'f410'],
  ['window maximize outline', 'f2d0'],
  ['window minimize outline', 'f2d1'],
  ['window restore outline', 'f2d2'],
  ['disk outline', 'f369'],

  // Outline Aliases
  ['heart empty', 'f004'],
  ['star empty', 'f089'],
])

export default name => fontAwesomeIcons.get(name)

/**
 * TODO We should probably declare a @fontface rule here
 */
