backend:
  name: git-gateway
  branch: master
media_folder: "static/uploads"
publish_mode: editorial_workflow
collections:
  - name: "components"
    label: "Components"
    folder: "content/components"
    create: false
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        required: false
        widget: "datetime"
      - label: "Draft"
        name: "draft"
        required: false
        widget: "boolean"
        default: true
      - label: "Best Practices (Do)"
        name: "do"
        widget: "list"
        default: []
      - label: "Best Practices (Don't)"
        name: "dont"
        widget: "list"
        default: []
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "learn"
    label: "Learn"
    folder: "content/learn"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        required: false
        widget: "datetime"
      - label: "Draft"
        name: "draft"
        required: false
        widget: "boolean"
        default: true
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "styles"
    label: "Styles"
    folder: "content/styles"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        required: false
        widget: "datetime"
      - label: "Draft"
        name: "draft"
        required: false
        widget: "boolean"
        default: true
      - label: "Body"
        name: "body"
        widget: "markdown"
