name: now.sh
on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: amondnet/now-deployment@v1
        id: now-deployment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          # https://zeit.co/docs/v2/advanced/platform/users-and-teams/#selecting-a-scope-for-api-requests
          zeit-team-id: team_HCvZAhI4QrAW964lPLfkz3bB
