export { default as Dialog } from './components/Dialog/dialogVariables'
export { default as Icon } from './components/Icon/iconVariables'
export { default as Loader } from './components/Loader/loaderVariables'
export { default as ProviderBox } from './components/Provider/providerBoxVariables'
export { default as Text } from './components/Text/textVariables'
