export { default as Dialog } from './components/Dialog/dialogStyles'
export { default as Icon } from './components/Icon/iconStyles'
export { default as Loader } from './components/Loader/loaderStyles'
export { default as ProviderBox } from './components/Provider/providerBoxStyles'
export { default as Text } from './components/Text/textStyles'
